<a href="https://colab.research.google.com/github/priyanka2611/MachineLearning/blob/master/pandas_matplotlib_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from functools import reduce  #reduce is used when u want consolidated result over sequence
l1=[3,5,1,2,6]
sum =reduce(lambda x,y : x+y,l1)
print(sum)

17


In [4]:
l1=[1,4,2,7,44,21]
l2= list(map(lambda x:x*2,l1))   # map helps to map a task on all elements
print(l2)

[2, 8, 4, 14, 88, 42]


In [3]:
l1=[2,4,22,3,6,7]

l2= list(filter(lambda x:(x%2==0),l1)) #filter(list and parameter) convert to list

print(l2)

[2, 4, 22, 6]


In [2]:
g= lambda x: x*x

g(10)


100

In [43]:
#pandas(data manupulations) matplotlib(plotting, visulaization) numpy(numerical computing)

#numpy: have multidimentional computing
import numpy as np

n1= np.array([10,20,30,40])
print(n1)
print('----')
n2= np.array([[1,2,3], [4,5,6]])
print(n2)
print('----')

n3=np.zeros((5,5))
print(n3)
print('----')
n4=np.full((3,4), 4)
print(n4)
print('----')
n5=np.arange(10,20)
print(n5)
print('----')
n6=np.arange(10,20, 5)
print(n6)
print('----')
n7=np.random.rand(2,5)
print(n7)
print('----')
n8=np.random.randint(2,50,5)
print(n8)

print('----')
a1= np.array([[1,2,4,5],[4,6,3,2]])
a1.shape
a1.shape= (4,2)
a1

#stack array : verically, horizontally, columnwise

a2=np.array([1,5,4,3,2])
a3=np.array([4,7,9,4,0])
x1=np.vstack((a2,a3)) #vertically stack
print(x1)
print('----')
x2=np.hstack((a2,a3))# horixonatlly stack
print(x2)
print('----')
x3=np.column_stack((a2,a3)) # stack column visw
print(x3)
print('----')
#intersect1d(common of both array values)
q2=np.array([1,5,4,3,2])
q3=np.array([1,7,9,2,0])
print(np.intersect1d(q2,q3))
print('----')
#setdiff1d(a,b)( uncommon elemts of a )
print(np.setdiff1d(q2,q3))
print('----')


#add arrays .sum
e2=np.array([1,5,4,3,2])
e3=np.array([1,7,9,2,0])
print(np.sum([e2,e3])) #add all ements
print('----')
print(np.sum([e2,e3],axis= 0))
print('----')
print(np.sum([e2,e3],axis= 1)) #add column elements
print('----')
print(e3+1) #add1 to each
print('--mean--')
#mean , , 
print(np.mean(e3))
print('--std dev--')
print(np.std(e3))
print('-median---')
print(np.median(e3))


#numpy save and load
print('saveload')
c1= np.save('file1', e3)

p= np.load('file1.npy')
print(p)


[10 20 30 40]
----
[[1 2 3]
 [4 5 6]]
----
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
----
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
----
[10 11 12 13 14 15 16 17 18 19]
----
[10 15]
----
[[0.47416325 0.44050831 0.44346234 0.19946661 0.68577172]
 [0.29842764 0.62204747 0.40975777 0.93775528 0.34687637]]
----
[49 19 11 48 30]
----
[[1 5 4 3 2]
 [4 7 9 4 0]]
----
[1 5 4 3 2 4 7 9 4 0]
----
[[1 4]
 [5 7]
 [4 9]
 [3 4]
 [2 0]]
----
[1 2]
----
[3 4 5]
----
34
----
[ 2 12 13  5  2]
----
[15 19]
----
[ 2  8 10  3  1]
--mean--
3.8
--std dev--
3.54400902933387
-median---
2.0
saveload
[1 7 9 2 0]


In [0]:
#PANDAS